# Generated by Django 2.1 on 2018-08-09 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Клініки',
                'verbose_name': 'Клініка',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=32)),
                ('disease_en', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Захворювання',
                'verbose_name': 'Захворювання',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Райони',
                'verbose_name': 'Район',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Clinic')),
            ],
            options={
                'verbose_name_plural': 'Лікарі',
                'verbose_name': 'Лікар',
            },
        ),
        migrations.CreateModel(
            name='Firstname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Імена',
                'verbose_name': "Ім'я",
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.IntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Doctor')),
            ],
            options={
                'verbose_name_plural': 'Щеплення',
                'verbose_name': 'Щеплення',
            },
        ),
        migrations.CreateModel(
            name='Lastname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Фамілії',
                'verbose_name': 'Фамілія',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=32)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.District')),
            ],
            options={
                'verbose_name_plural': 'Населені пункти',
                'verbose_name': 'Населений пункт',
            },
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doses', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Clinic')),
            ],
            options={
                'verbose_name_plural': 'Журнал обліку',
                'verbose_name': 'Запис у журналі',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('sex', models.BooleanField()),
                ('firstname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Firstname')),
                ('lastname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Lastname')),
            ],
            options={
                'verbose_name_plural': 'Пацієнти',
                'verbose_name': 'Пацієнт',
            },
        ),
        migrations.CreateModel(
            name='Patronymic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'По-батькові',
                'verbose_name': 'По-батькові',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Області',
                'verbose_name': 'Область',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=32)),
                ('expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Серії',
                'verbose_name': 'Серія',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(blank=True, max_length=64, null=True)),
                ('vaccine_en', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True)),
                ('manufacturer_en', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=16, null=True)),
                ('country_en', models.CharField(blank=True, max_length=16, null=True)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('disease', models.ManyToManyField(blank=True, to='registry.Disease')),
            ],
            options={
                'verbose_name_plural': 'Вакцини',
                'verbose_name': 'Вакцина',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Vaccine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patronymic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Patronymic'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Series'),
        ),
        migrations.AddField(
            model_name='immunization',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Patient'),
        ),
        migrations.AddField(
            model_name='immunization',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Series'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='firstname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Firstname'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Lastname'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patronymic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Patronymic'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Region'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Locality'),
        ),
    ]
