# Generated by Django 2.1 on 2018-08-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Профілі',
                'verbose_name': 'Профіль',
            },
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['clinic'], 'verbose_name': 'Клініка', 'verbose_name_plural': 'Клініки'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['disease'], 'verbose_name': 'Захворювання', 'verbose_name_plural': 'Захворювання'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['district'], 'verbose_name': 'Район', 'verbose_name_plural': 'Райони'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['locality'], 'verbose_name': 'Населений пункт', 'verbose_name_plural': 'Населені пункти'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['region'], 'verbose_name': 'Область', 'verbose_name_plural': 'Області'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['vaccine'], 'verbose_name': 'Вакцина', 'verbose_name_plural': 'Вакцини'},
        ),
        migrations.RenameField(
            model_name='firstname',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='lastname',
            old_name='name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='patronymic',
            old_name='name',
            new_name='patronymic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='info',
            field=models.CharField(default=django.utils.timezone.now, max_length=265),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Clinic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Locality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
