# Generated by Django 2.1 on 2018-08-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_patient_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Клініка', 'verbose_name_plural': 'Клініки'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Захворювання', 'verbose_name_plural': 'Захворювання'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Райони'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Лікар', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterModelOptions(
            name='firstname',
            options={'verbose_name': "Ім'я", 'verbose_name_plural': 'Імена'},
        ),
        migrations.AlterModelOptions(
            name='immunization',
            options={'verbose_name': 'Щеплення', 'verbose_name_plural': 'Щеплення'},
        ),
        migrations.AlterModelOptions(
            name='lastname',
            options={'verbose_name': 'Фамілія', 'verbose_name_plural': 'Фамілії'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Населений пункт', 'verbose_name_plural': 'Населені пункти'},
        ),
        migrations.AlterModelOptions(
            name='logbook',
            options={'verbose_name': 'Запис у журналі', 'verbose_name_plural': 'Журнал обліку'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пацієнт', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterModelOptions(
            name='patronymic',
            options={'verbose_name': 'По-батькові', 'verbose_name_plural': 'По-батькові'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Області'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серія', 'verbose_name_plural': 'Серії'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'Вакцина', 'verbose_name_plural': 'Вакцини'},
        ),
        migrations.AddField(
            model_name='vaccine',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
