# Generated by Django 2.1 on 2018-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20180814_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='info',
            field=models.TextField(blank=True, max_length=265, null=True),
        ),
    ]
