# Generated by Django 2.1 on 2018-08-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20180805_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
