# Generated by Django 2.1 on 2018-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20180824_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['-id'], 'verbose_name': 'Клініка', 'verbose_name_plural': 'Клініки'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id'], 'verbose_name': 'Лікар', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterModelOptions(
            name='immunization',
            options={'ordering': ['-id'], 'verbose_name': 'Щеплення', 'verbose_name_plural': 'Щеплення'},
        ),
        migrations.AlterModelOptions(
            name='logbook',
            options={'ordering': ['-id'], 'verbose_name': 'Запис у журналі', 'verbose_name_plural': 'Журнал обліку'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id'], 'verbose_name': 'Пацієнт', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-id'], 'verbose_name': 'Серія', 'verbose_name_plural': 'Серії'},
        ),
        migrations.AlterField(
            model_name='immunization',
            name='dose',
            field=models.FloatField(default=1),
        ),
    ]
