# Generated by Django 2.1 on 2018-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20180830_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='arrival',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
